version: '3.8'
services:
  db:
    image: mongo
    restart: 'always'
    container_name: Spotify
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db # Để dữ liệu không bị mất khi tắt Docker